### ISSUE TITLE
Setup Github Repository Structure

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#3]
Determine how you want to organize the repository for now. You will be working on individual visualizations at first, and then jointly on more complex visualizations. You may want individual subdirectories at first, and then a subdirectory for each joint visualization later.

**Comment by ranmocy** [comment]
@sjengle Currently the exercise visualizations are under `gh-pages` branches. Each person use a separated subdir, and will add links to the `index.html`.

The way we will cooperate with each other is by using the Pull Request system.
So we will work on individual branches instead of individual subdirs.
