### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by sjengle** [cs690/fall2014-sonicwall#68]
Please complete a **Final Report** by **Thursday December 11** at 11:59pm.
## Submission

Upload a PDF on Canvas for the [Final Report](https://usfca.instructure.com/courses/1298673/assignments/5462941) assignment. Please also email the PDF to me (sjengle@cs.usfca.edu) and Carrie Gates (Carrie_Gates@dell.com), and CC **everyone** in the group (using your @usfca.edu emails) and EJ Jung (ejung@cs.usfca.edu).
## Requirements

Use the description posted on Canvas at:

> https://usfca.instructure.com/courses/1298673/assignments/5462941

I will create another issue with descriptions of the other deliverables I expect for this course.

---

@ranmocy  @yaxum62   @Azure22   @michellegg

**Comment by ranmocy** [comment]
@sjengle I'm wondering how to finish the documentation part. In the Canvas description, it should be included inside of the Deliverables chapter.
Since it's a visualization project, the user interface should be the self-documentation. Can I use the deliverable page in #69 as a documentation, which includes Usage Video and Slides?
Thank you.

**Comment by sjengle** [comment]
The usage videos could suffice for the documentation part. You should mention that there are usage videos in the report, and how to obtain them.

**Comment by ranmocy** [comment]
Got it, thank you.

**Comment by ranmocy** [comment]
Submited and emailed
